### ISSUE TITLE
How to remove Entando?

### ISSUE THREAD

**Issue by sinanasiriamirbande** [entando/entando-docs#270]
i installed Entando with 
`https://multipass.run/#install`
`curl -sfL https://get.entando.org | bash
`
now I want to remove it from my machine.
how can I do that?
thanks in advancece

**Comment by nshaw** [comment]
Hi, @sinanasiriamirbande.

You have a couple of options. If you want to completely remove the VM created by Multipass then you can use multipass delete entando (where the last option is the VM name) and then you can use multipass purge to recover the resources. If you just want to shutdown Entando but keep the VM you can use multipass shell entando to shell into the VM and then remove the namespace via sudo kubectl delete namespace/entando. There are other tips here: https://dev.entando.org/v6.3/docs/reference/local-tips-and-tricks.html#quickstart-management.

I'd encourage you to use the Entando forum or slack for additional questions since typically repository issues are specifically for issues related to that codebase. See https://dev.entando.org/v6.3/docs/community/contributing.html#get-help for more information.

Cheers,
Nathan
